### ISSUE TITLE
LazRichView not used

### ISSUE THREAD

**Issue by rchastain** [MFernstrom/rTest#1]
Hello! Nice little program. But here I have a simple TMemo in the main window. The LazRichView and SynEdit packages are declared but not used. So nothing is highlighted in the editor. Program tested under Windows 10, with Lazarus 2.0.0.
By the way, I made almost the same program, but using the RichMemo component.
Regards.
Roland

**Comment by MFernstrom** [comment]
Thanks :)

And thanks for the heads up, I did forget some cleanup from a previous attempt but ran into issues with richmemo (That I believe have since been fixed)

I might go back and add highlights and whatnot now that I have RichMemo working with skalogryz latest revision.

I'll leave this open until I've cleaned up/fixed though so I don't forget.

**Comment by MFernstrom** [comment]
There we go, just committed a slightly cleaner version b8c115f04ddf835442c235a6fc7642c0521f6912
